steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: global
      list_align: after_alias
      long_list_align: multiline
      list_padding: 4
      separate_lists: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true

  - tabs:
      spaces: 2

  - trailing_whitespace: {}

columns: 80

newline: native

language_extensions: []
