resolver: lts-8.20
packages:
  - '.'
  - location: './library/opaleye/'
    extra-dep: yes
  - location: './library/tisch/'
    extra-dep: yes
  - location: '../katip/katip/'
    extra-dep: yes
extra-deps: []
flags: {}
extra-package-dbs: []
