name: edible
version: '0.0.0.0'
synopsis: TODO
description: TODO
category: Database
author: TODO
maintainer: TODO
copyright: TODO
license: TODO
github: tomjaguarpaw/haskell-opaleye.git
homepage: TODO
bug-reports: TODO
tested-with: GHC==8.0.1 GHC==7.10.3 GHC==7.8.4 GHC==7.6.3
dependencies:
- aeson
- attoparsec
- base
- base16-bytestring
- bytestring
- case-insensitive
- contravariant
- exceptions
- lens
- mtl
- postgresql-simple
- pretty
- product-profunctors
- profunctors
- scientific
- semigroups
- singletons
- tagged
- text
- time
- time-locale-compat
- transformers
- uuid
- void
library:
  source-dirs: src
  ghc-options: -Wall
